# https://docs.pytest.org/en/stable/customize.html
[tool.pytest.ini_options]
addopts = "--alluredir allure-results"
markers = [
    "query_post",
    "query_posts",
    "mutation_post_delete",
    "mutation_post_update",
    "mutation_post_create",
    "query_user",
    "query_users"]

log_file = "log_tests.txt"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s - %(name)s - [%(levelname)8s] %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
